export const INCREASE_COUNTER_ASYNC='INCREASE_COUNTER_ASYNC';
export const DECREASE_COUNTER_ASYNC='DECREASE_COUNTER_ASYNC';
export const DECREASE_COUNTER='DECREASE_COUNTER';
export const INCREASE_COUNTER='INCREASE_COUNTER';

